# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f8f4b5;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_add_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_back.setGeometry(QtCore.QRect(10, 560, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.btn_add_back.setFont(font)
        self.btn_add_back.setStyleSheet("QPushButton{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"background-color: #f88c34;\n"
"}")
        self.btn_add_back.setObjectName("btn_add_back")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.name_vvod = QtWidgets.QLineEdit(self.centralwidget)
        self.name_vvod.setGeometry(QtCore.QRect(40, 130, 191, 20))
        self.name_vvod.setStyleSheet("QLineEdit {\n"
"    border:1px solid black;\n"
"    border-radius:5px;\n"
"}")
        self.name_vvod.setObjectName("name_vvod")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rec_vvod = QtWidgets.QTextEdit(self.centralwidget)
        self.rec_vvod.setGeometry(QtCore.QRect(40, 200, 401, 241))
        self.rec_vvod.setStyleSheet("QTextEdit {\n"
"    border:1px solid black;\n"
"    border-radius:5px;\n"
"}")
        self.rec_vvod.setObjectName("rec_vvod")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(120, 460, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"background-color: #f88c34;\n"
"}")
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_add_back.setText(_translate("MainWindow", "< Назад"))
        self.label.setText(_translate("MainWindow", "Добавление своего рецепта"))
        self.label_2.setText(_translate("MainWindow", "Введите название нового блюда:"))
        self.label_3.setText(_translate("MainWindow", "Напишите рецепт приготовления блюда:"))
        self.btn_save.setText(_translate("MainWindow", "Сохранить"))
