# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_okno.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 640)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 160, 311, 301))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color: #f88c34;\n"
"    border:3px solid #404040;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_recepty = QtWidgets.QPushButton(self.frame)
        self.btn_recepty.setGeometry(QtCore.QRect(60, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(11)
        self.btn_recepty.setFont(font)
        self.btn_recepty.setStyleSheet("QPushButton{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"}")
        self.btn_recepty.setFlat(True)
        self.btn_recepty.setObjectName("btn_recepty")
        self.btn_skach = QtWidgets.QPushButton(self.frame)
        self.btn_skach.setGeometry(QtCore.QRect(60, 220, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.btn_skach.setFont(font)
        self.btn_skach.setAutoFillBackground(False)
        self.btn_skach.setStyleSheet("QPushButton{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"}")
        self.btn_skach.setAutoDefault(False)
        self.btn_skach.setDefault(False)
        self.btn_skach.setFlat(True)
        self.btn_skach.setObjectName("btn_skach")
        self.btn_add = QtWidgets.QPushButton(self.frame)
        self.btn_add.setGeometry(QtCore.QRect(60, 170, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.btn_add.setFont(font)
        self.btn_add.setAutoFillBackground(False)
        self.btn_add.setStyleSheet("QPushButton{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"}")
        self.btn_add.setAutoDefault(False)
        self.btn_add.setDefault(False)
        self.btn_add.setFlat(True)
        self.btn_add.setObjectName("btn_add")
        self.text_main = QtWidgets.QLabel(self.frame)
        self.text_main.setGeometry(QtCore.QRect(20, 40, 271, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_main.sizePolicy().hasHeightForWidth())
        self.text_main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.text_main.setFont(font)
        self.text_main.setToolTipDuration(-1)
        self.text_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text_main.setAutoFillBackground(False)
        self.text_main.setStyleSheet("QLabel{\n"
"border:1px;\n"
"}")
        self.text_main.setLineWidth(8)
        self.text_main.setAlignment(QtCore.Qt.AlignCenter)
        self.text_main.setObjectName("text_main")
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_user.setFont(font)
        self.label_user.setAutoFillBackground(False)
        self.label_user.setStyleSheet("QLabel{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"background-color: #f88c34;\n"
"}")
        self.label_user.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_user.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_user.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user.setObjectName("label_user")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 478, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Книга рецептов"))
        self.btn_recepty.setText(_translate("MainWindow", "Рецепты"))
        self.btn_skach.setText(_translate("MainWindow", "Скачать видео с Youtube"))
        self.btn_add.setText(_translate("MainWindow", "Добавить свой рецепт"))
        self.text_main.setText(_translate("MainWindow", "CookBook"))
        self.label_user.setText(_translate("MainWindow", "none"))
