# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recepty.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    background-color: #f8f4b5;\n"
"}")
        self.label.setObjectName("label")
        self.btn_rec_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rec_back.setGeometry(QtCore.QRect(10, 560, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.btn_rec_back.setFont(font)
        self.btn_rec_back.setStyleSheet("QPushButton{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"background-color: #f88c34;\n"
"}")
        self.btn_rec_back.setObjectName("btn_rec_back")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 80, 461, 441))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color: #83865b;\n"
"    border:1px solid #404040;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.list_rec = QtWidgets.QListWidget(self.frame)
        self.list_rec.setGeometry(QtCore.QRect(20, 20, 151, 301))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.list_rec.setFont(font)
        self.list_rec.setStyleSheet("QListWidget {\n"
"    border-radius: 10px;\n"
"    border:1px solid #404040;\n"
"    background-color: #f8f4b5;\n"
"}")
        self.list_rec.setObjectName("list_rec")
        self.text_rec = QtWidgets.QTextEdit(self.frame)
        self.text_rec.setGeometry(QtCore.QRect(200, 20, 241, 381))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.text_rec.setFont(font)
        self.text_rec.setStyleSheet("QTextEdit {\n"
"    border-radius: 10px;\n"
"    border:1px solid #404040;\n"
"    background-color: #f8f4b5;\n"
"}")
        self.text_rec.setObjectName("text_rec")
        self.btn_enter = QtWidgets.QPushButton(self.frame)
        self.btn_enter.setGeometry(QtCore.QRect(20, 350, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.btn_enter.setFont(font)
        self.btn_enter.setStyleSheet("QPushButton{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"background-color: #f88c34;\n"
"}")
        self.btn_enter.setObjectName("btn_enter")
        self.btn_del = QtWidgets.QPushButton(self.frame)
        self.btn_del.setGeometry(QtCore.QRect(20, 380, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.btn_del.setFont(font)
        self.btn_del.setStyleSheet("QPushButton{\n"
"border:2px solid #404040;\n"
"border-radius: 10px;\n"
"background-color: #f88c34;\n"
"}")
        self.btn_del.setObjectName("btn_del")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Рецепты"))
        self.btn_rec_back.setText(_translate("MainWindow", "< Назад"))
        self.btn_enter.setText(_translate("MainWindow", "Показать"))
        self.btn_del.setText(_translate("MainWindow", "Удалить"))
